### ISSUE TITLE
Keep only standard chromosomes in `geneplotter` figure

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/geneplotter#4]

**Comment by LiNk-NY** [comment]
Hi Vince, @vjcitn 

It took a look at this and it seems to be using an old (partialy?) deprecated class `chromLocation`. 
I didn't find an easy way to prune the chromosome names as mentioned in the meeting with `GenomeInfoDb::keepStandardChromosomes`. 

Perhaps you know the easy way to prune them? 

-Marcel

cc: @jwokaty

**Comment by vjcitn** [comment]
I don't.  The
CHR map for chip hgu95av2 (object of class "ProbeAnnDbBimap")
is going to be hard to work with.  BUT
```
cPlot(chrObj, as.character(1:22))
```
gets something much more reasonable!

**Comment by jwokaty** [comment]
Thanks, this seems to work. Shall I close the issue?
